name: Bug Report
description: Report an issue or unexpected behaviour
labels: ['bug', 'status: needs investigating']
body:
  - type: markdown
    attributes:
      value: |
        Before reporting an issue here, please make sure you are on the latest version of Quests.
  - type: textarea
    attributes:
      label: Description of Bug
      description: Describe what went wrong, and what the expected behaviour was.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: |
        Describe any steps or details instructions to reproduce this bug.
        Please include any screenshots or videos, or list steps, if possible.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment
      description: |
        State the Minecraft version and server software this bug is present on. Please also include other versions of relevant versions.
        You can identify your server software by running `/version`, and your Quests version by running `/version Quests`.
        **Note:** simply stating "Latest version" is **not** enough! You must include the actual version!
      value: |
          - Minecraft version:
          - Server software:
          - Quests version:
  - type: checkboxes
    attributes:
      label: Agreements
      description: Please agree to the following.
      options:
        - label: I am running the latest version of Quests
          required: true
        - label: I am certain this issue is unique and a similar issue is not currently open
          required: true
        - label: I am using a version of Minecraft which is supported by Quests
          required: true
  - type: textarea
    attributes:
      label: Other
      description: |
        Please include other helpful information below.
        This field is not required.
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        Thank you for taking your time to file this bug report.
