name: Feature Request
description: Request a new feature or suggest new ideas
labels: ['enhancement', 'status: needs investigating']
body:
  - type: markdown
    attributes:
      value: |
        Before requesting a new feature, please make sure you are on the latest version of Quests.
  - type: textarea
    attributes:
      label: Description of Feature
      description: Describe what you would like added to Quests. Videos or screenshots are welcome.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reason for Addition
      description: |
        Explain your reasoning for wanting this addition.
        This may include a problem you're trying to solve, or any context for this request.
        This field is not required.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Alternative Solutions
      description: Discuss any other solutions you have tried to achieve what you wanted.
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Agreements
      description: Please agree to the following.
      options:
        - label: I am running the latest version of Quests
          required: true
        - label: I am certain this request is unique and a similar issue is not currently open
          required: true
  - type: textarea
    attributes:
      label: Other
      description: |
        Please include other helpful information below.
        This field is not required.
    validations:
      required: false
